insert into Rol values ('ticket_ver','Para poder ver el contenido de un ticket'),
						('ticket_listar','Para poder listar los ticket'),
						('ticket_crear','Para crear un ticket'),
						('ticket_editar','Para poder editar/responder un ticket'),
						('ticket_asignar','Permite hacer hasignaciones de operadores en un ticket'),
						('ticket_departamento','Permite asignar / cambiar de departamento'),
						('ticket_sla','Permite cambiar el plan SLA de un ticket'),
						('informes_usuarios','Permite a un operador ver informes de usuarios'),
						('informes_operadores','Permite a un Operador ver informes de otros operadores'),
						('informes_ampliados','Permite ampliar la visibilidad a todos los departamentos'),
						('informes_widgets','Permite usar los widgets de informes'),
						('anuncios_ver','Permite ver los anuncios'),
						('anuncios_listar','Permite ver el listado de anuncios'),
						('anuncios_crear','Permite crear un anuncio'),
						('anuncios_ediar','Permite editar un anuncio'),
						('anuncios_eliminar','Permite eliminar un anuncio'),
						('categorias_ver','Poder ver las categorias existentes'),
						('categorias_crear','Permite crear una categoria de anuncios'),
						('categorias_editar','Permite editar una categoría'),
						('categorias_eliminar','Permite eliminar una categoría'),
						('tipoTicket_ver','Permite ver los tipos de tickets existentes'),
						('tipoTicket_crear','Permite crear nuevos tipos de tickets'),
						('tipoTicket_editar','Permite editar un tipo de ticket'),
						('tipoTicket_eliminar','Permite eliminar un tipo de ticket'),	
						('general_parametros','Permite configurar los parámetros generales del sistema'),
						('general_plantillas','Permite configurar las plantillas de correo'),						
						('sla_ver','Permite listar y ver los SLAs'),
						('sla_crear','Permite crear un SLA'),
						('sla_editar','Permite editar un SLA'),
						('sla_eliminar','Permite eliminar un sla'),
						('prioridades_ver','Permite ver y listar las prioridades'),
						('prioridades_crear','Permite Crear prioridades'),
						('prioridades_editar','Permite editar Prioridades'),
						('prioridades_eliminar','Permite eliminar prioridades'),
						('estados_ver','Permite ver y listar los estados'),
						('estados_crear','Permite Crear estados'),
						('estados_editar','Permite editar estados'),
						('estadoss_eliminar','Permite eliminar estados'),			
						('usuarios_ver','Permite ver y listar a los usuarios'),
						('usuarios_crear','Permite crear un usuario'),
						('usuarios_editar','Permite editar un usuarios'),
						('usuarios_eliminar','Permite eliminar a usuarios'),
						('usuarios_asignar','Permite asignar usuarios a empresas'),
						('empresas_ver','Permite ver y listar empresas'),
						('empresas_crear','Permite crear empresas'),
						('empresas_editar','Permite editar a una empresa'),
						('empresas_eliminar','Permite eliminar empresas'),	
						('operadores_ver','Permite ver y listar a operadores'),
						('operadores_crear','Permite crear operadores'),
						('operadores_editar','Permite editar operadores'),
						('operadores_eliminar','Permite eliminar operadores'),
						('perfiles_ver','Permite ver los perfiles'),
						('perfiles_crear','Permite crear perfiles'),
						('perfiles_editar','Permite editar perfiles'),
						('perfiles_eliminar','Permite eliminar los perfiles');
						
						
						