<?php

namespace Proxies\__CG__\Modelo;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LogModificacionTicket extends \Modelo\LogModificacionTicket implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'logId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'responsable', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'usuarioId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'operadorId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'slaId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'accion', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'fecha', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'ticket'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'logId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'responsable', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'usuarioId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'operadorId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'slaId', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'accion', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'fecha', '' . "\0" . 'Modelo\\LogModificacionTicket' . "\0" . 'ticket'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (LogModificacionTicket $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getLogId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getLogId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogId', []);

        return parent::getLogId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResponsable($responsable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResponsable', [$responsable]);

        return parent::setResponsable($responsable);
    }

    /**
     * {@inheritDoc}
     */
    public function getResponsable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResponsable', []);

        return parent::getResponsable();
    }

    /**
     * {@inheritDoc}
     */
    public function setUsuarioId($usuarioId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsuarioId', [$usuarioId]);

        return parent::setUsuarioId($usuarioId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsuarioId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsuarioId', []);

        return parent::getUsuarioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperadorId($operadorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperadorId', [$operadorId]);

        return parent::setOperadorId($operadorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperadorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperadorId', []);

        return parent::getOperadorId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlaId($slaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlaId', [$slaId]);

        return parent::setSlaId($slaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getSlaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlaId', []);

        return parent::getSlaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccion($accion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccion', [$accion]);

        return parent::setAccion($accion);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccion', []);

        return parent::getAccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicket(\Modelo\Ticket $ticket = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicket', [$ticket]);

        return parent::setTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicket', []);

        return parent::getTicket();
    }

}
