<?php

namespace Proxies\__CG__\Modelo;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Mensajes extends \Modelo\Mensajes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'mensajeId', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'texto', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'fecha', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'tipoMensaje', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'creadorOperador', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'creadorUsuario', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'ticket', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'archivo'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'mensajeId', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'texto', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'fecha', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'tipoMensaje', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'creadorOperador', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'creadorUsuario', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'ticket', '' . "\0" . 'Modelo\\Mensajes' . "\0" . 'archivo'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Mensajes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setMensajeId($mensajeId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMensajeId', [$mensajeId]);

        return parent::setMensajeId($mensajeId);
    }

    /**
     * {@inheritDoc}
     */
    public function getMensajeId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMensajeId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMensajeId', []);

        return parent::getMensajeId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTexto($texto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTexto', [$texto]);

        return parent::setTexto($texto);
    }

    /**
     * {@inheritDoc}
     */
    public function getTexto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTexto', []);

        return parent::getTexto();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha($fecha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', [$fecha]);

        return parent::setFecha($fecha);
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoMensaje($tipoMensaje)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoMensaje', [$tipoMensaje]);

        return parent::setTipoMensaje($tipoMensaje);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoMensaje()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoMensaje', []);

        return parent::getTipoMensaje();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreadorOperador($creadorOperador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreadorOperador', [$creadorOperador]);

        return parent::setCreadorOperador($creadorOperador);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreadorOperador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreadorOperador', []);

        return parent::getCreadorOperador();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreadorUsuario($creadorUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreadorUsuario', [$creadorUsuario]);

        return parent::setCreadorUsuario($creadorUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreadorUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreadorUsuario', []);

        return parent::getCreadorUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicket(\Modelo\Tickets $ticket)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicket', [$ticket]);

        return parent::setTicket($ticket);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicket()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicket', []);

        return parent::getTicket();
    }

    /**
     * {@inheritDoc}
     */
    public function addArchivo(\Modelo\Archivos $archivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArchivo', [$archivo]);

        return parent::addArchivo($archivo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArchivo(\Modelo\Archivos $archivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArchivo', [$archivo]);

        return parent::removeArchivo($archivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArchivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArchivo', []);

        return parent::getArchivo();
    }

}
