<?php

namespace Proxies\__CG__\Modelo;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Empresa extends \Modelo\Empresa implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'empresaId', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'razonSocial', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'pais', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'direccion', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'ciudad', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'telefono', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'web', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'ultimaActualizacion', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'anuncio'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'empresaId', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'razonSocial', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'pais', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'direccion', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'ciudad', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'codigoPostal', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'telefono', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'web', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'ultimaActualizacion', '' . "\0" . 'Modelo\\Empresa' . "\0" . 'anuncio'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Empresa $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEmpresaId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEmpresaId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaId', []);

        return parent::getEmpresaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazonSocial($razonSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazonSocial', [$razonSocial]);

        return parent::setRazonSocial($razonSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazonSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazonSocial', []);

        return parent::getRazonSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setDireccion($direccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDireccion', [$direccion]);

        return parent::setDireccion($direccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDireccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDireccion', []);

        return parent::getDireccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCiudad($ciudad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCiudad', [$ciudad]);

        return parent::setCiudad($ciudad);
    }

    /**
     * {@inheritDoc}
     */
    public function getCiudad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCiudad', []);

        return parent::getCiudad();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodigoPostal($codigoPostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodigoPostal', [$codigoPostal]);

        return parent::setCodigoPostal($codigoPostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodigoPostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodigoPostal', []);

        return parent::getCodigoPostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefono($telefono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefono', [$telefono]);

        return parent::setTelefono($telefono);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefono', []);

        return parent::getTelefono();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeb($web)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeb', [$web]);

        return parent::setWeb($web);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeb()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeb', []);

        return parent::getWeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimaActualizacion($ultimaActualizacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimaActualizacion', [$ultimaActualizacion]);

        return parent::setUltimaActualizacion($ultimaActualizacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaActualizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaActualizacion', []);

        return parent::getUltimaActualizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function addAnuncio(\Modelo\Anuncio $anuncio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAnuncio', [$anuncio]);

        return parent::addAnuncio($anuncio);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAnuncio(\Modelo\Anuncio $anuncio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAnuncio', [$anuncio]);

        return parent::removeAnuncio($anuncio);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnuncio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnuncio', []);

        return parent::getAnuncio();
    }

}
