<?php

namespace Proxies\__CG__\Modelo;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Anuncio extends \Modelo\Anuncio implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'anuncioId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'empresaId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'titulo', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'contenido', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'fechaCreacion', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'estado', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'fechaFinPublicacion', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'operadorId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'categoria', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'empresa'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'anuncioId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'empresaId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'titulo', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'contenido', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'fechaCreacion', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'estado', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'fechaFinPublicacion', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'operadorId', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'categoria', '' . "\0" . 'Modelo\\Anuncio' . "\0" . 'empresa'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Anuncio $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setAnuncioId($anuncioId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnuncioId', [$anuncioId]);

        return parent::setAnuncioId($anuncioId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnuncioId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAnuncioId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnuncioId', []);

        return parent::getAnuncioId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmpresaId($empresaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmpresaId', [$empresaId]);

        return parent::setEmpresaId($empresaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresaId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getEmpresaId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresaId', []);

        return parent::getEmpresaId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenido($contenido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenido', [$contenido]);

        return parent::setContenido($contenido);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenido', []);

        return parent::getContenido();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaCreacion($fechaCreacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaCreacion', [$fechaCreacion]);

        return parent::setFechaCreacion($fechaCreacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaCreacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaCreacion', []);

        return parent::getFechaCreacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinPublicacion($fechaFinPublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinPublicacion', [$fechaFinPublicacion]);

        return parent::setFechaFinPublicacion($fechaFinPublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinPublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinPublicacion', []);

        return parent::getFechaFinPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperadorId($operadorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperadorId', [$operadorId]);

        return parent::setOperadorId($operadorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperadorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperadorId', []);

        return parent::getOperadorId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria(\Modelo\CategoriaAnuncios $categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function addEmpresa(\Modelo\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEmpresa', [$empresa]);

        return parent::addEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEmpresa(\Modelo\Empresa $empresa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEmpresa', [$empresa]);

        return parent::removeEmpresa($empresa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmpresa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmpresa', []);

        return parent::getEmpresa();
    }

}
