<?php

namespace Proxies\__CG__\Modelo;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TicketFiltros extends \Modelo\TicketFiltros implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'filtroId', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'nombre', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'departamentos', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'estados', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'prioridades', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'asignadoAMi', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'operadores'];
        }

        return ['__isInitialized__', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'filtroId', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'nombre', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'departamentos', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'estados', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'prioridades', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'asignadoAMi', '' . "\0" . 'Modelo\\TicketFiltros' . "\0" . 'operadores'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TicketFiltros $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getFiltroId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getFiltroId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiltroId', []);

        return parent::getFiltroId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombre($nombre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombre', [$nombre]);

        return parent::setNombre($nombre);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombre', []);

        return parent::getNombre();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamentos($departamentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamentos', [$departamentos]);

        return parent::setDepartamentos($departamentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamentos', []);

        return parent::getDepartamentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstados($estados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstados', [$estados]);

        return parent::setEstados($estados);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstados', []);

        return parent::getEstados();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioridades($prioridades)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioridades', [$prioridades]);

        return parent::setPrioridades($prioridades);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioridades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioridades', []);

        return parent::getPrioridades();
    }

    /**
     * {@inheritDoc}
     */
    public function setAsignadoAMi($asignadoAMi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAsignadoAMi', [$asignadoAMi]);

        return parent::setAsignadoAMi($asignadoAMi);
    }

    /**
     * {@inheritDoc}
     */
    public function getAsignadoAMi()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAsignadoAMi', []);

        return parent::getAsignadoAMi();
    }

    /**
     * {@inheritDoc}
     */
    public function setOperadores($operadores)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOperadores', [$operadores]);

        return parent::setOperadores($operadores);
    }

    /**
     * {@inheritDoc}
     */
    public function getOperadores()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOperadores', []);

        return parent::getOperadores();
    }

}
